### PR TITLE
Replace `graph.load()` with `graph.parse()`

### PR DESCRIPTION
**Pull request by eggplants**
fix: #186
I'll convert this into `ready to merge` after #184 is merged.

### CODE REVIEW

**Review by aucampia — APPROVED** [review]

**Review by nicholascar — APPROVED** [review]

**Comment by eggplants** [comment]
>Ran 1512 tests in 894.352s
>FAILED (failures=3, errors=211, skipped=549, expected failures=80)

I have to need to research this change's effect more.

**Comment by eggplants** [comment]
https://rdflib.readthedocs.io/en/stable/_modules/rdflib/graph.html#Graph.load

```python
class Graph(Node):
...
    def load(self, source, publicID=None, format="xml"):
        warn(
            DeprecationWarning(
                "graph.load() is deprecated, it will be removed in rdflib 6.0.0. "
                "Please use graph.parse() instead."
            )
        )
        return self.parse(source, publicID, format)
...
```

**Comment by eggplants** [comment]
https://rdflib.readthedocs.io/en/stable/_modules/rdflib/graph.html#ConjunctiveGraph.parse

```python
class Graph(Node):
...
    def parse(
        self,
        source=None,
        publicID=None,
        format=None,
        location=None,
        file=None,
        data=None,
        **args,
    ):
        """
        Parse source adding the resulting triples to its own context
        (sub graph of this graph).

        See :meth:`rdflib.graph.Graph.parse` for documentation on arguments.

        :Returns:

        The graph into which the source was parsed. In the case of n3
        it returns the root context.
        """

        source = create_input_source(
            source=source,
            publicID=publicID,
            location=location,
            file=file,
            data=data,
            format=format,
        )

        g_id = publicID and publicID or source.getPublicId()
        if not isinstance(g_id, Node):
            g_id = URIRef(g_id)

        context = Graph(store=self.store, identifier=g_id)
        context.remove((None, None, None))  # hmm ?
        context.parse(source, publicID=publicID, format=format, **args)
        # TODO: FIXME: This should not return context, but self.
        return context
...
```

**Comment by eggplants** [comment]
I overlooked the fact that the default format is different in `load` (`"xml"`) and `parse` (`None`).

**Comment by nicholascar** [comment]
Yes, default format used to be XML but now it's Turtle.

**Comment by eggplants** [comment]
Is it suitable to do hard coding instead of using const?

**Review by nicholascar — APPROVED** [review]

**Pull request merged**
