### PR TITLE
Goodbye, `rdflib-jsonld`

### PR DESCRIPTION
**Pull request by eggplants**
rdflib 6.0.1 had marged rdflib-jsonld. So I say goodbye to rdflib-jsonld.

### CODE REVIEW

**Comment by aucampia** [comment]
Thanks for the PRs, I will reivew as soon as I have some time, hopefully tonight or tomorrow night (CET)

**Comment by nicholascar** [comment]
Please bump the RDFlib requirements up further to 6.1.1, not 6.0.1. The later version has a few important fixes

**Comment by eggplants** [comment]
𝙍𝙚𝙖𝙙𝙮 𝙛𝙤𝙧 𝙧𝙚𝙫𝙞𝙚𝙬…

**Review by aucampia — APPROVED** [review]
Thanks for the change, looks good, apologies for not getting to a review earlier. I changed the python version constraint to match.

**Review by nicholascar — APPROVED** [review]
Looks good

**Pull request merged**
