### PR TITLE
Added requirements.txt to manifest

### LINKED ISSUE #66: packaging broken
Hi guys, seeing another pip install failure on our build server as of release 1.7.3

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20151105-4556-o9zodr" ----
STDOUT: Collecting rdflib (from -r requirements.txt (line 1))
Downloading rdflib-4.2.1.tar.gz (889kB)
Collecting statsd (from -r requirements.txt (line 2))
Downloading statsd-3.2.1-py2.py3-none-any.whl
Collecting lshash==0.0.4dev (from -r requirements.txt (line 3))
Downloading lshash-0.0.4dev.tar.gz
Collecting knowsis.commons[stats] (from -r requirements.txt (line 4))
Downloading https://repo.fury.io/knowsis/
Collecting isodate (from rdflib->-r requirements.txt (line 1))
Downloading isodate-0.5.4.tar.gz
Collecting pyparsing (from rdflib->-r requirements.txt (line 1))
Downloading pyparsing-2.0.5-py2.py3-none-any.whl
Collecting SPARQLWrapper (from rdflib->-r requirements.txt (line 1))
Downloading SPARQLWrapper-1.7.3.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-uBrAyp/SPARQLWrapper/setup.py", line 45, in <module>
requirements = list(parse_requirements('requirements.txt', session=PipSession()))
File "/home/knowsis/releases/7283cfc3f18343475889e947570c2f1a295f5c36/env/lib/python2.7/site-packages/pip/req/req_file.py", line 77, in parse_requirements
filename, comes_from=comes_from, session=session
File "/home/knowsis/releases/7283cfc3f18343475889e947570c2f1a295f5c36/env/lib/python2.7/site-packages/pip/download.py", line 416, in get_file_content
'Could not open requirements file: %s' % str(exc)
pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### PR DESCRIPTION
**Pull request by PandaWill**
Fixes #66

### CODE REVIEW

**Comment by davidread** [comment]
@wikier are you able to review and merge this asap? This is breaking our CI too.

**Comment by wikier** [comment]
+1

**Comment by wikier** [comment]
:+1:

**Comment by wikier** [comment]
@PandaWill, @davidread: what CI?

**Comment by davidread** [comment]
Thanks @wikier and can you update PyPI too?

The CIs are referenced on the issue - see the bottom

**Comment by wikier** [comment]
@davidread [1.7.4](https://pypi.python.org/pypi/SPARQLWrapper/1.7.4) has been uploaded, apologize for the mistake

**Comment by wikier** [comment]
@davidread, @PandaWill: a PR include such check in our CI would be cool ;-)

**Comment by davidread** [comment]
Perfect, many thanks @wikier

**Comment by PandaWill** [comment]
@wikier We could change the install step for the CI to be:

    python setup.py sdist && pip install ./dist/*

How does that sound?

**Comment by wikier** [comment]
so what you suggest @PandaWill  is to us use directly `setuptools` instead of `pip` as we have now https://github.com/RDFLib/sparqlwrapper/blob/master/.travis.yml#L18 ?

**Pull request merged**
