### PR TITLE
Port code to py3 and drop py2 code

### PR DESCRIPTION
**Pull request by t0b3**
@nicholascar I found time to port codebase to py3, drop unused legacy py2 code and simplify the test call. Finally I fixed a test issue, errors didn't show up in travis results.

### CODE REVIEW

**Comment by nicholascar** [comment]
@t0b3 This is a really neat tidy-up! Only the necessary changes made, looks good. 

I've asked @dayures & @wikier to review as they are the main SPARQLWrapper maintainers and I'd like to wait a few days to give them a chance to do so. If they don't raise any objections by Wednesday (5 days from now) I'll merge this in. Thanks for the work.

**Comment by dayures** [comment]
related issue #16

**Comment by dayures** [comment]
thanks for your help and spirit!

**Comment by nicholascar** [comment]
Merging since this have been approved by @dayures

**Comment by rchateauneu** [comment]
What is please the latest sparqlwrapper version which officially works with Python 2 ? Thanks.

**Comment by nicholascar** [comment]
I guess that is [1.8.5](https://pypi.org/project/SPARQLWrapper/#history) which was released on PyPI in December last year. 

This merge will only kick in with a new release which we might call 2.0.0 in a few weeks from now. We haven’t come out with a proper development and release plan but, in general, we just want to tidy up code (style only) and fold in a few of the existing Pull Requests and that will make for a good 2.0.0.

**Comment by t0b3** [comment]
@nicholascar it would be great to have a new release with native support for py3 cause the current release depends on 2to3 conversion which is being phased out ... i.e. https://bugs.gentoo.org/812236
btw: I really don't care the numbers 1.8.6 or 2.0.0 or whatever...

**Comment by nicholascar** [comment]
I'm not extremely motivated to put much effort into SPARQLWrapper as I find that a few lines of `requests` or `httpx` do most of the SPARQL interactions I need! I assume that before `requests` the value proposition of SPARQLWrapper over `urllib` was greater...

That said, it's reasonably popular and people do care about it still so I'm happy to maintain things and I _might_ get motivated to develop too, if I can be convinced that using SPARQLWrapper is much better than  a few lines of `requests` or `httpx`. I do make lots of Python-to-SPARQL calls each day for work (i.e. this isn't just a hobby).

@t0b3 would you be interested in taking the lead on the update you mentioned above - new release - and perhaps SPARQLWrapper in general? If you do, I will assist.

**Comment by t0b3** [comment]
I imagined releasing just the current master straight away by
1. add a tag i.e. `1.8.6`
2. release this with `Tagging version 1.8.5 release of SPARQLWrapper.`

In case there would be more demanding requests I join you in feeling more resources shall be added.

**Pull request merged**
